/*

	define arrays for convoys

	[[waypointpositions], [classname, position, spawndirection]], // (convoyID 0)
	[[waypointpositions], [classname, position, spawndirection]] // (convoyID 1)
	etc

*/
[
	[
		[
		"getPos bwConvoyWp_1",
		"getPos bwConvoyWp_2",
		"getPos bwConvoyWp_3",
		"getPos bwConvoyWp_4",
		"getPos bwConvoyWp_5"
		],
		[
		["Redd_Tank_LKW_leicht_gl_Wolf_Flecktarn_Moerser", 		"getPos bwConvoyPos_1", 		"getDir bwConvoyPos_1"],
	    ["Redd_Tank_Fuchs_1A4_Pi_Flecktarn", 						"getPos bwConvoyPos_2", 		"getDir bwConvoyPos_1"],
	    ["Redd_Tank_Fuchs_1A4_Pi_Flecktarn", 					"getPos bwConvoyPos_3", 		"getDir bwConvoyPos_1"],
	    ["Redd_Tank_Fuchs_1A4_Pi_Flecktarn", 					"getPos bwConvoyPos_4", 		"getDir bwConvoyPos_1"],
	    ["Redd_Tank_Fuchs_1A4_Pi_Flecktarn", 					"getPos bwConvoyPos_5",			"getDir bwConvoyPos_1"],
	    ["Redd_Tank_Fuchs_1A4_San_Flecktarn", 					"getPos bwConvoyPos_6", 		"getDir bwConvoyPos_1"],
	    ["Redd_Tank_Fuchs_1A4_Pi_Flecktarn", 						"getPos bwConvoyPos_7", 		"getDir bwConvoyPos_1"],
	    ["Redd_Tank_LKW_leicht_gl_Wolf_Flecktarn_Moerser", 		"getPos bwConvoyPos_8", 		"getDir bwConvoyPos_1"]
	    ]
	],
	[
		[
		"getPos civWp_1",
		"getPos civWp_2",
		"getPos civWp_3",
		"getPos civWp_4",
		"getPos civWp_5",
		"getPos civWp_6",
		"getPos civWp_7",
		"getPos civWp_8",
		"getPos civWp_9",
		"getPos civWp_10",
		"getPos civWp_11",
		"getPos civWp_12",
		"getPos civWp_13",
		"getPos civWp_14",
		"getPos civWp_15",
		"getPos civWp_16",
		"getPos civWp_17",
		"getPos civWp_18",
		"getPos civWp_19",
		"getPos civWp_20",
		"getPos civWp_21",
		"getPos civWp_22",
		"getPos civWp_23",
		"getPos civWp_24",
		"getPos civWp_25",
		"getPos civWp_26",
		"getPos civWp_27",
		"getPos civWp_28",
		"getPos civWp_29",
		"getPos civWp_30",
		"getPos civWp_31",
		"getPos civWp_32",
		"getPos civWp_33",
		"getPos civWp_34",
		"getPos civWp_35",
		"getPos civWp_36",
		"getPos civWp_37",
		"getPos civWp_38",
		"getPos civWp_39",
		"getPos civWp_40",
		"getPos civWp_41",
		"getPos civWp_42",
		"getPos civWp_43",
		"getPos civWp_44",
		"getPos civWp_45",
		"getPos civWp_46"
		],
		[
		["rhs_tigr_m_msv", 				"getPos civConvoyPos_1", 		"getDir civConvoyPos_1"],
	    ["rhs_btr80a_msv", 				"getPos civConvoyPos_2", 		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_msv", 				"getPos civConvoyPos_3", 		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_msv", 				"getPos civConvoyPos_4", 		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_msv", 				"getPos civConvoyPos_5",		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_msv", 				"getPos civConvoyPos_6", 		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_ammo_msv", 				"getPos civConvoyPos_7", 		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_ammo_msv", 				"getPos civConvoyPos_8", 		"getDir civConvoyPos_1"],
	    ["RHS_Ural_Fuel_MSV_01", 				"getPos civConvoyPos_9", 		"getDir civConvoyPos_1"],
	    ["RHS_Ural_Fuel_MSV_01", 				"getPos civConvoyPos_10", 		"getDir civConvoyPos_1"],
	    ["RHS_Ural_Fuel_MSV_01", 				"getPos civConvoyPos_11", 		"getDir civConvoyPos_1"],
	    ["RHS_Ural_Fuel_MSV_01", 				"getPos civConvoyPos_12", 		"getDir civConvoyPos_1"],
	    ["RHS_BM21_MSV_01", 				"getPos civConvoyPos_13",		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_msv", 				"getPos civConvoyPos_14", 		"getDir civConvoyPos_1"],
	    ["rhs_gaz66_msv", 				"getPos civConvoyPos_15", 		"getDir civConvoyPos_1"],
	    ["rhs_btr80a_msv", 				"getPos civConvoyPos_16", 		"getDir civConvoyPos_1"],
	    ["rhs_tigr_m_msv", 				"getPos civConvoyPos_17",		"getDir civConvoyPos_1"]
	    ]
	],
	[
		[
		"getPos civWp_1",
		"getPos civWp_2",
		"getPos civWp_3",
		"getPos civWp_4",
		"getPos civWp_5",
		"getPos civWp_6",
		"getPos civWp_7",
		"getPos civWp_8"
		],
		[
		["rhs_btr70_vdv", 				"getPos civConvoyPos_1", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_2", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_3", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_4", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_5",		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_6", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_7", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_8", 		"getDir civConvoyPos_1"],
	    ["rhs_btr70_vdv", 				"getPos civConvoyPos_9", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_10", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_11", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_12", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_13",		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_14", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_15", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_16", 		"getDir civConvoyPos_1"],
	    ["RDS_Van_01_box_F", 				"getPos civConvoyPos_17",		"getDir civConvoyPos_1"]
	    ]
	],
	[
		[
		"getPos civWp_1",
		"getPos civWp_2",
		"getPos civWp_3",
		"getPos civWp_4",
		"getPos civWp_5",
		"getPos civWp_6",
		"getPos civWp_7",
		"getPos civWp_8",
		"getPos civWp_9",
		"getPos civWp_10",
		"getPos civWp_11",
		"getPos civWp_12",
		"getPos civWp_13",
		"getPos civWp_14",
		"getPos civWp_15",
		"getPos civWp_16",
		"getPos civWp_17",
		"getPos civWp_18",
		"getPos civWp_19",
		"getPos civWp_20",
		"getPos civWp_21",
		"getPos civWp_22",
		"getPos civWp_23",
		"getPos civWp_24",
		"getPos civWp_25",
		"getPos civWp_26",
		"getPos civWp_27",
		"getPos civWp_28",
		"getPos civWp_29",
		"getPos civWp_30",
		"getPos civWp_31",
		"getPos civWp_32",
		"getPos civWp_33",
		"getPos civWp_34",
		"getPos civWp_35",
		"getPos civWp_36",
		"getPos civWp_37",
		"getPos civWp_38",
		"getPos civWp_39",
		"getPos civWp_40",
		"getPos civWp_41",
		"getPos civWp_42",
		"getPos civWp_43",
		"getPos civWp_44",
		"getPos civWp_45",
		"getPos civWp_46"
		],
		[
		["rhs_t72ba_tv", 				"getPos civConvoyPos_1", 		"getDir civConvoyPos_1"],
	    ["rhs_t72bb_tv", 				"getPos civConvoyPos_2", 		"getDir civConvoyPos_1"],
	    ["rhs_t72ba_tv", 				"getPos civConvoyPos_3", 		"getDir civConvoyPos_1"]
	    ]
	]
]
